### PR TITLE
Minshare

### PR DESCRIPTION
**Pull request by ParthKolekar**
Added a minshare
But this has to be decided early on.

Please do tell me if you want branches

### CODE REVIEW

**Comment by nehaljwani** [comment]
Personally, I am against restrictions. Also, there are no 'admins', so putting a restriction doesn't sound cool to me. @ffledgling what say?

**Comment by ParthKolekar** [comment]
Well... IN3O wanted a minshare limit of 2e10 to prevent leaches. 

I just implemented that. ¯_(ツ)_/¯

**Comment by ffledgling** [comment]
So multiple issues with the patch, if plan to go ahead with accepting the feature (which I think is up for a little debate).
1. There seem to be unrelated changes in this PR
   - Changes to the install scripts
   - Actual changes for the min-share feature.
2. The PR seems to have tons of commits from your local branch (merge with upstream/master). I suggest you submit a PR/Patch against a clean copy of master. We can't add those 6 other commits into the repo. Look into how `git rebase` works, or simply nuke your old repo if it doesn't contain anything important and re-apply your relevant changes.

**Comment by ParthKolekar** [comment]
Yes... Which is why I asked if you wanted branches....
Internal collage stuff makes squashing commits a boring task. 

Will send another PR by taking your head, instead of my head.

**Pull request closed without merging**
